
[DATA_NODE.business_data]
storage_type = "csv"
default_path = "data/yelp_business.csv"
scope = "GLOBAL:SCOPE"

[DATA_NODE.review_data]
storage_type = "generic"
read_fct = "config.config.get_data:function"
read_fct_params = ["data/yelp_review.csv"]
write_fct = "config.config.write_function:function"
scope = "GLOBAL:SCOPE"

[DATA_NODE.business_name]
storage_type = "pickle"
default_data = "\"Mon Ami Gabi\""
scope = "SCENARIO:SCOPE"

[DATA_NODE.business_id]
storage_type = "pickle"
scope = "SCENARIO:SCOPE"

[DATA_NODE.raw_reviews]
storage_type = "pickle"
scope = "SCENARIO:SCOPE"

[DATA_NODE.parsed_reviews]
storage_type = "pickle"
scope = "SCENARIO:SCOPE"

[TASK.get_business_id]
inputs = ["business_name:SECTION", "business_dict:SECTION"]
outputs = ["business_id:SECTION"]
function = "algos.algos.get_id_from_name:function"
skippable = "True:bool"

[TASK.get_reviews]
inputs = ["business_id:SECTION", "review_data:SECTION"]
outputs = ["raw_reviews:SECTION"]
function = "algos.algos.get_business_data:function"
skippable = "True:bool"

[TASK.parse_reviews]
inputs = ["raw_reviews:SECTION"]
outputs = ["parsed_reviews:SECTION"]
function = "algos.algos.parse_business_data:function"
skippable = "True:bool"

[DATA_NODE.business_dict]
storage_type = "pickle"
scope = "GLOBAL:SCOPE"

[TASK.create_business_dict]
inputs = ["business_data:SECTION"]
outputs = ["business_dict:SECTION"]
function = "algos.algos.create_business_dict:function"
skippable = "True:bool"

[PIPELINE.pipeline]
tasks = [
  "create_business_dict:SECTION",
  "get_business_id:SECTION",
  "get_reviews:SECTION",
  "parse_reviews:SECTION",
]

[SCENARIO.scenario]
pipelines = ["pipeline:SECTION"]
